# Retro
# Theme create by: https://github.com/puszkarek
# Update by(sort by time):

# Thank you!

code_syntax_highlight = "gruvbox"

# border
file_panel_border = "#ff3845"
sidebar_border = "#ff3845"
footer_border = "#ff3845"

# border active
file_panel_border_active = "#fb932e"
sidebar_border_active = "#fb932e"
footer_border_active = "#fb932e"
modal_border_active = "#fb932e"

# background (bg)
full_screen_bg = "#0e0e17"
file_panel_bg = "#0e0e17"
sidebar_bg = "#0e0e17"
footer_bg = "#0e0e17"
modal_bg = "#030305"

# foreground (fg)
full_screen_fg = "#ff3845"
file_panel_fg = "#ff3845"
sidebar_fg = "#ff3845"
footer_fg = "#ff3845"
modal_fg = "#ff3845"

# special color
cursor = "#ff3845"
correct = "#ff00ff"
error = "#ff2e6e"
hint = "#2570d4"
cancel = "#ff2e6e"
gradient_color = ["#ff3845", "#ff3845"]

# file panel special items
file_panel_top_directory_icon = "#ff3845"
file_panel_top_path = "#ff3845"
file_panel_item_selected_fg = "#fb932e"
file_panel_item_selected_bg = "#0e0e17"

# sidebar special items
sidebar_title = "#ff3845"
sidebar_item_selected_fg = "#fb932e"
sidebar_item_selected_bg = "#0e0e17"
sidebar_divider = "#ff3845"

# modal special items
modal_cancel_fg = "#0e0e17"
modal_cancel_bg = "#ff2e6e"

modal_confirm_fg = "#0e0e17"
modal_confirm_bg = "#ff3845"

# help menu
help_menu_hotkey = "#ff3845"
help_menu_title = "#ff3845"
