# Retro
# Theme create by: https://github.com/puszkarek
# Update by(sort by time):

# Thank you!

code_syntax_highlight = "gruvbox"

# border
file_panel_border = "#33ff00"
sidebar_border = "#33ff00"
footer_border = "#33ff00"

# border active
file_panel_border_active = "#ffb000"
sidebar_border_active = "#ffb000"
footer_border_active = "#ffb000"
modal_border_active = "#ffb000"

# background (bg)
full_screen_bg = "#0a0e0a"
file_panel_bg = "#0a0e0a"
sidebar_bg = "#0a0e0a"
footer_bg = "#0a0e0a"
modal_bg = "#121a12"

# foreground (fg)
full_screen_fg = "#33ff00"
file_panel_fg = "#33ff00"
sidebar_fg = "#33ff00"
footer_fg = "#33ff00"
modal_fg = "#33ff00"

# special color
cursor = "#33ff00"
correct = "#ff00ff"
error = "#ff2e6e"
hint = "#00e1ff"
cancel = "#ff2e6e"
gradient_color = ["#33ff00", "#33ff00"]

# file panel special items
file_panel_top_directory_icon = "#33ff00"
file_panel_top_path = "#33ff00"
file_panel_item_selected_fg = "#ffb000"
file_panel_item_selected_bg = "#0a0e0a"

# sidebar special items
sidebar_title = "#33ff00"
sidebar_item_selected_fg = "#ffb000"
sidebar_item_selected_bg = "#0a0e0a"
sidebar_divider = "#33ff00"

# modal special items
modal_cancel_fg = "#0a0e0a"
modal_cancel_bg = "#ff2e6e"

modal_confirm_fg = "#0a0e0a"
modal_confirm_bg = "#33ff00"

# help menu
help_menu_hotkey = "#33ff00"
help_menu_title = "#33ff00"
