[ui]
font_color = "#ff3845"

main_foreground_color = "#ff3845"
secondary_foreground_color = "#ff3845"

main_background_color = "#0e0e17"
secondary_background_color = "#0e0e17"

[others]
selection_highlight_color = "#fb932e"
environment_variable_highlight_color = "#2570d4"

[methods]
GET = "#0f630c"
POST = "#49360b"
PUT = "#0b4949"
PATCH = "#0b2849"
DELETE = "#490b0b"
HEAD = "#0f630c"
OPTIONS = "#490b49"