version: 1.0.0
log:
    path: /tmp/vi-mongo.log
    level: info
    prettyPrint: true
editor:
    command: vim
    env: ""
showConnectionPage: true
showWelcomePage: true
currentConnection: Local
connections:
    - url: mongodb://localhost:27017/
      host: localhost
      port: 27017
      database: ""
      username: ""
      password: ""
      name: Local
      timeout: 5
      options: {}
styles:
    betterSymbols: true
    currentStyle: retro.yaml
